### ISSUE TITLE
建议添加乘方

### ISSUE THREAD

**Issue by cheny0y0** [itorr/homo#15]
如30226801971775055948247051683954096612865741943=(11-4)⁵¹⁺⁴

还有24328178969534828711372998093524038624549939291093897594803044627929851847630171468204018048158313071545558582878941443575997789023924896396443875395359349770542481860688423018931112868941207904563690988057526655233314223037469642908934552090184747450875044775139194778995850939282164937224365003798549244827515814790192482532503820209785176997120505581871652020283345699498870297715544463788187251651993922748519338634709140872078361254965575827591798863011422165221700780231881064907563714719998422745303896108725452114484557610869850001597254124937864011004638867797213729987434724487525634876149422385520870715213620143394748395396583239166358150084763971206465371425813478981308410214382083153545892754605700019264312047488480890809426380721037533398647137766639665971166306068666670689826463298268468365727780154826438496260078380561785575277930954678504630198248803749046717600583109070952973067395710111879898170626763632283526208560813084575121484414059519760779830442546147624648197239125131554522285642404630262047553358838678070994196008177405845585571841=11^4^5^1^4

**Comment by VirtualOilCake** [comment]
这个数字太大了，超出了JS的int

**Comment by cheny0y0** [comment]
用Python重写罢（无慈悲）

**Comment by ren-yc** [comment]
> 用Python重写罢（无慈悲）

Python？你是认真的吗😕

**Comment by cheny0y0** [comment]
> > 用Python重写罢（无慈悲）
> 
> 
> 
> Python？你是认真的吗😕

Python3的int事无限大的，只要内存够，多少位都行

**Comment by itorr** [comment]
`**` 运算符 得出的数确实有点太大了，用 JavaScript 无法方便的验算，暂时不考虑
