### ISSUE TITLE
输入 3.14 无法得出结果

### ISSUE THREAD

**Issue by kouhe3** [itorr/homo#17]
![image](https://user-images.githubusercontent.com/25522053/154197809-3a36c648-a604-40e1-99cb-3f6b4892541b.png)

![image](https://user-images.githubusercontent.com/25522053/154197864-a788a5b6-583c-45c9-98cd-dbf8afae9f07.png)

Chrome 版本 99.0.4844.27.

**Comment by itorr** [comment]
https://github.com/itorr/homo/commit/ad970845a4b38cf85565d24758627ca03699ee7c
