### ISSUE TITLE
增加对小数的支持

### ISSUE THREAD

**Issue by kouhe3** [itorr/homo#3]
比如
` 3.14 = ((1-14)*-(5+1)*4+(-11+4-5+14))/(1*(1+4)*5*1*4) `

**Comment by itorr** [comment]
思路有了🤣先乘到整再除回来。但感觉不够优雅😕

**Comment by itorr** [comment]
支持了💩
https://github.com/itorr/homo/commit/467fa44ceb66c9c8a554a67ec71b75b5418c7c77

**Comment by kouhe3** [comment]
@itorr 
这一次一次地除十实在蛋疼。。就不能一次除100吗？

**Comment by itorr** [comment]
@kouhe3 
都是除已经很不优雅了🌞 帮我想想别的实现方式呀

**Comment by kouhe3** [comment]
我上面那个算式是3.14＝314/100
先计算100，再放到算式里除，而不是一次一次除10 @itorr
