### ISSUE TITLE
Found 11/(45-1)*4 bug of `homo()`

### ISSUE THREAD

**Issue by onion108** [itorr/homo#30]
<img width="994" alt="スクリーンショット 2022-07-18 15 59 41" src="https://user-images.githubusercontent.com/57032603/179468353-6912637d-74a9-42fe-a881-4075c09db5b6.png">

As you can see in the image, when using `-Infinity` as the value of the input, `homo()` gave us `"(11-4-5+1-4)*这么恶臭的Infinity有必要论证吗"` , where the expected  result is `"这么恶臭的-Infinity有必要论证吗"` .  

Therefore, here is your final result: ` WA, 90 `.

**Comment by cloudhzc** [comment]
how can you input `-Infinity` ?

**Comment by onion108** [comment]
> 

Use the inspector and remove the value of the attribute `type` of this input element.
