### ISSUE TITLE
输入数值为0.1时结果出错

### ISSUE THREAD

**Issue by Jim-Zhang-517** [itorr/homo#5]
如图，希望可以修复，另外希望可以加入负数及小数论证。
![Screenshot_20200407-005720](https://user-images.githubusercontent.com/28817939/78584740-3e489780-786b-11ea-85c9-edab3bc7a545.png)

**Comment by itorr** [comment]
支持了💩
https://github.com/itorr/homo/commit/467fa44ceb66c9c8a554a67ec71b75b5418c7c77
