### ISSUE TITLE
page报错

### ISSUE THREAD

**Issue by chenxuuu** [itorr/homo#6]
firefox 75.0：

SyntaxError: invalid regexp group           homo.js:1:1

![图片](https://user-images.githubusercontent.com/10357394/78859543-3737aa00-7a62-11ea-89b5-1f22fb446413.png)

edge build 18363：

![图片](https://user-images.githubusercontent.com/10357394/78859648-939ac980-7a62-11ea-85ec-85d3f30309d9.png)

SCRIPT5018: SCRIPT5018: Unexpected quantifier      homo.js (10,23)

**Comment by itorr** [comment]
忘记火狐不支持 lookahead 了😱 感谢提交

**Comment by chenxuuu** [comment]
那edge是什么情况。。

**Comment by itorr** [comment]
@chenxuuu 同一个问题，等之后我换个写法或者欢迎提交 Pull

**Comment by itorr** [comment]
已修复
https://github.com/itorr/homo/commit/205538fc8cbf29025ebb81b117d2a9633ae67ab0
