### ISSUE TITLE
部分状况*后面的括号赘余。

### ISSUE THREAD

**Issue by rcswex** [itorr/homo#8]
如：13113456196 = 114514*(114514)，其中的括号赘余。

**Comment by itorr** [comment]
确实，一直拖着没处理。这里我的思路是靠正则替换、但是规则的细节没有考虑完整，有兴趣欢迎提交 pull😭

**Comment by steve02081504** [comment]
> 确实，一直拖着没处理。这里我的思路是靠正则替换、但是规则的细节没有考虑完整，有兴趣欢迎提交 pull😭

循环匹配`\(([^\+\)\-]+)\)`替换成`\1`直至匹配不到应该就行。。
